name: Docker Build Tests
on:
  workflow_call:
jobs:
  docker_build_tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build .
