name: Docker Build Tests
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"
jobs:
  docker_build_tests:
    timeout-minutes: 15
    runs-on: ${{inputs.runner}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build image
        run: docker build .
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2