name: Docker Build Tests
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"
      platforms:
        type: string
        required: false
        default: linux/amd64
jobs:
  docker_build_tests:
    timeout-minutes: 15
    runs-on: ${{inputs.runner}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ inputs.platforms }}
      - name: Build image
        run: docker buildx build --platform=${{ inputs.platforms }} .