name: Docker Build Tests
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"
      platforms:
        type: string
        required: false
        default: linux/amd64
      dockerfile:
        type: string
        default: Dockerfile
      build_timeout:
        type: int
        default: 60
jobs:
  docker_build_tests:
    timeout-minutes: ${{ inputs.build_timeout }}
    runs-on: ${{inputs.runner}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ inputs.platforms }}
          install: true
      - name: Build image
        run: docker build --platform=${{ inputs.platforms }} -f ${{inputs.dockerfile}} .
