name: Propose Stable Release
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"
      version_file:
        type: string
        default: "version.py"
      on_version_change:
        type: string
        default: ""
      release_type:
        type: string
      setup_py:
        type: string
        default: "setup.py"
      update_changelog:
        type: boolean
        default: false
      changelog_file:
        type: string
        default: "CHANGELOG.md"
      changelog_max_issues:
        type: number
        default: 50
      branch:
        type: string
        default: "dev"
      alpha_var:
        type: string
        required: false
      build_var:
        type: string
        required: false
      minor_var:
        type: string
        required: false
      major_var:
        type: string
        required: false
    outputs:
      version:
        description: Updated version
        value: ${{jobs.bump_version.outputs.version}}
      changelog:
        description: Changelog Contents
        value: ${{jobs.update_changelog.outputs.changelog}}

jobs:
  bump_version:
    runs-on: ${{inputs.runner}}
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v2
        with:
          path: action/github/
          repository: NeonGeckoCom/.github
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Increment Version
        id: version
        run: |
          if [ -z ${{ inputs.alpha_var }} ]; then
            python action/github/scripts/oneline_semantic_version_bump.py action/package/${{ inputs.version_file }} ${{ inputs.release_type }}
          else
            python action/github/scripts/multiline_semantic_version_bump.py action/package/${{ inputs.version_file }} \
              ${{ inputs.release_type }} ${{ inputs.alpha_var }} ${{ inputs.build_var }} ${{ inputs.minor_var }} ${{ inputs.major_var }}
          fi
          echo ::set-output name=version::$(python action/package/${{ inputs.setup_py }} --version)
      - name: Run Extra Update Script
        if: "${{ inputs.on_version_change != '' }}"
        run: |
          python action/package/${{ inputs.on_version_change }} ${{ steps.version.outputs.version }}
      - name: Push Version Change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increment Version to ${{ steps.version.outputs.version }}
          repository: action/package/
  update_changelog:
    needs: bump_version
    runs-on: ${{inputs.runner}}
    if: ${{ inputs.update_changelog }}
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
      - name: Check Latest Release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: draft,prerelease
        continue-on-error: true
      - name: Generate Changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: action/package/${{ inputs.changelog_file }}
          futureRelease: ${{needs.bump_version.outputs.version}}
          maxIssues: ${{ inputs.changelog_max_issues }}
          sinceTag: ${{ steps.latest_release.outputs.release }}
      - name: Push Changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog
          repository: action/package/