name: Publish Alpha Build
on:
  workflow_call:
    inputs:
      version_file:
        type: string
        default: "version.py"
      setup_py:
        type: string
        default: "setup.py"
      branch:
        type: string
        default: ${{ github.ref }}
      publish_prerelease:
        type: boolean
        default: False
      publish_pypi:
        type: boolean
        default: True
      version_scheme:
        type: string
        default: semver
      update_changelog:
        type: boolean
        default: false
      changelog_file:
        type: string
        default: "CHANGELOG.md"
      changelog_max_issues:
        type: number
        default: 50
    outputs:
      version:
        description: Updated Alpha version
        value: ${{jobs.bump_version.outputs.version}}
      changelog:
        description: Changelog Contents
        value: ${{jobs.update_changelog.outputs.changelog}}
jobs:
  bump_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v2
        with:
          path: action/github/
          repository: NeonGeckoCom/.github
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Increment Alpha Version
        id: version
        run: |
          if [ ${{ inputs.version_scheme }} == "semver" ]; then
            python action/github/scripts/oneline_semantic_version_bump.py action/package/${{ inputs.version_file }} alpha
          elif [ ${{ inputs.version_scheme }} == "dated" ]; then
            python action/github/scripts/dated_version_bump.py action/package/${{ inputs.version_file }} true
          fi
          echo ::set-output name=version::$(python action/package/${{ inputs.setup_py }} --version)
      - name: Push Version Change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increment Version to ${{ steps.version.outputs.version }}
          repository: action/package/
  update_changelog:
    needs: bump_version
    runs-on: ubuntu-latest
    if: ${{ inputs.update_changelog }}
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
      - name: Check Latest Release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: draft,prerelease
        continue-on-error: true
      - name: Generate Changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: action/package/${{ inputs.changelog_file }}
          futureRelease: ${{needs.bump_version.outputs.version}}
          maxIssues: ${{ inputs.changelog_max_issues }}
          sinceTag: ${{ steps.latest_release.outputs.release }}
      - name: Push Changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog
          repository: action/package/
  build_and_publish_pypi:
    if: ${{ always() && inputs.publish_pypi }}
    needs:
      - update_changelog
      - bump_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v2
        with:
          path: action/github/
          repository: NeonGeckoCom/.github
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Build Distribution Packages
        run: |
          cd action/package
          python ${{ inputs.setup_py }} bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: action/package/dist/
          password: ${{secrets.PYPI_TOKEN}}
  tag_prerelease:
    needs:
      - update_changelog
      - bump_version
    if: ${{ always() && inputs.publish_prerelease }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
      - name: Create Pre-release
        uses: ncipollo/release-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{needs.bump_version.outputs.version}}
          commit: ${{ github.ref }}
          prerelease: true
          generateReleaseNotes: true