name: Publish Alpha Build
on:
  workflow_call:
    inputs:
      version_file:
        type: string
        default: "version.py"
      setup_py:
        type: string
        default: "setup.py"
    outputs:
      version:
        description: Updated Alpha version
        value: ${{jobs.build_and_publish_pypi.outputs.version}}
jobs:
  build_and_publish_pypi:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: action/package/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v2
        with:
          path: action/github/
          repository: NeonGeckoCom/.github
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Increment Alpha Version
        id: version
        run: |
          python action/github/scripts/version_bump.py action/package/${{ inputs.version_file }}
          echo ::set-output name=version::$(sed "s/a/-a./" <<< $(python action/package/${{ inputs.setup_py }} --version))
      - name: Push Version Change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increment Version
          repository: action/package/
      - name: Build Distribution Packages
        run: |
          python action/package/${{ inputs.setup_py }} bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{secrets.PYPI_TOKEN}}