name: Publish Docker Containers
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"
      setup_qemu:
        type: boolean
        default: false
      base_tag:
        type: string
        required: false
      extra_tag:
        type: string
        required: false
      registry:
        type: string
        default: ghcr.io
      image_name:
        type: string
        default: ${{ github.repository }}
      platforms:
        type: string
        required: false
        default: linux/amd64
      dockerfile:
        type: string
        default: Dockerfile
      build_args:
        type: string
      extra_build_args:
        type: string

env:
  REGISTRY: ${{ inputs.registry }}
  IMAGE_NAME: ${{ inputs.image_name }}

jobs:
  build_and_publish_docker:
    runs-on: ${{inputs.runner}}
    outputs:
      version: ${{ steps.version.version }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version
        id: version
        run: |
          VERSION=$(sed "s/a/-a./" <<< $(python setup.py --version))
          echo ::set-output name=version::${VERSION}
        env:
          image_name: ${{ env.IMAGE_NAME }}

      - name: Setup QEMU
        if: ${{ inputs.setup_qemu }}
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata for base Docker
        id: base_meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.version.outputs.version }}
            type=ref,event=branch
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.base_meta.outputs.tags }}
          labels: ${{ steps.base_meta.outputs.labels }}
          target: ${{ inputs.base_tag }}
          platforms: ${{ inputs.platforms }}
          file: ${{ inputs.dockerfile }}
          build-args: |
            ${{ inputs.build_args}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for extra Docker
        if: "${{ inputs.extra_tag != '' }}"
        id: extra_meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ inputs.extra_tag }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.version.outputs.version }}
            type=ref,event=branch
      - name: Build and push extra Docker image
        if: "${{ inputs.extra_tag != '' }}"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.extra_meta.outputs.tags }}
          labels: ${{ steps.extra_meta.outputs.labels }}
          target: ${{ inputs.extra_tag }}
          platforms: ${{ inputs.platforms }}
          file: ${{ inputs.dockerfile }}
          build-args: |
            ${{ inputs.extra_build_args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
