name: Publish Stable Build
on:
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: true
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"

jobs:
  tag_release:
    runs-on: ${{inputs.runner}}
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        run: |
          VERSION=$(python setup.py --version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - uses: ncipollo/release-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{env.VERSION}}
  build_and_publish_pypi:
    runs-on: ${{inputs.runner}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Build Distribution Packages
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{secrets.PYPI_TOKEN}}