name: Pull to Master
on:
  workflow_call:
    inputs:
      pr_reviewer:
        required: false
        type: string
      pr_assignee:
        required: false
        type: string
      destination:
        type: string
        default: "master"
      pr_title:
        type: string
      pr_body:
        type: string
      pr_draft:
        type: boolean
        default: true

jobs:
  pull_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request-action
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_reviewer: ${{ inputs.pr_reviewer }}
          pr_assignee: ${{ inputs.pr_assignee }}
          pr_draft: ${{ inputs.pr_draft }}
          pr_title: ${{ inputs.pr_title }}
          pr_body: ${{ inputs.pr_body }}