name: Python Build Tests
on:
  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: "3.8"
jobs:
  py_build_tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ inputs.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Build Distribution Packages
        run: |
          python setup.py bdist_wheel sdist

