name: Python Build Tests
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"
      python_version:
        required: false
        type: string
        default: "3.8"
      test_manifest:
        required: false
        type: boolean
        default: false
      manifest_ignored:
        required: false
        type: string
        default: "test/**"
      test_pipaudit:
        type: boolean
        default: false
      pipaudit_ignored:
        type: string
        default: "GHSA-r9hx-vwmv-q579 PYSEC-2022-43012"
jobs:
  py_build_tests:
    timeout-minutes: 15
    runs-on: ${{inputs.runner}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ inputs.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Build Distribution Packages
        run: |
          python setup.py bdist_wheel sdist
      - name: Test Manifest
        if: ${{ inputs.test_manifest }}
        uses: tj-actions/check-manifest@v1
        with:
          args: --ignore ${{ inputs.manifest_ignored }}
      - name: PIP Audit
        if: ${{ inputs.test_pipaudit }}
        uses: pypa/gh-action-pip-audit@v1.0.7
        with:
          ignore-vulns: ${{ inputs.pipaudit_ignored }}
