name: Skill Unit Tests
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"
      intent_file:
        type: string
        default: test/test_intents.yaml
      timeout:
        type: number
        default: 15
      test_padatious:
        type: boolean
        default: False
      test_padacioso:
        type: boolean
        default: True
jobs:
  test_intents_ovos:
    runs-on: ${{inputs.runner}}
    timeout-minutes: ${{inputs.timeout}}
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: action/skill/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v2
        with:
          repository: NeonGeckoCom/.github
          path: action/github/
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc libfann-dev swig libssl-dev portaudio19-dev git libpulse-dev
          pip install --upgrade pip
          pip install pytest mock ovos-core[skills,skills_lgpl] action/skill/
      - name: Test Skill Intents Padacioso
        if: ${{ inputs.test_padacioso }}
        run: |
          export INTENT_ENGINE="padacioso"
          export INTENT_TEST_FILE="action/skill/${{inputs.intent_file}}"
          pytest action/github/test/test_skill_intents.py
      - name: Test Skill Intents Padatious
        if: ${{ inputs.test_padatious }}
        run: |
          export INTENT_ENGINE="padatious"
          export INTENT_TEST_FILE="action/skill/${{inputs.intent_file}}"
          pytest action/github/test/test_skill_intents.py
  test_intents_neon:
    runs-on: ${{inputs.runner}}
    timeout-minutes: ${{inputs.timeout}}
    strategy:
      matrix:
        python-version: [ 3.7, '3.10' ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: action/skill/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v2
        with:
          repository: NeonGeckoCom/.github
          path: action/github/
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc libfann-dev swig libssl-dev portaudio19-dev git libpulse-dev
          pip install --upgrade pip
          pip install pytest mock git+https://github.com/NeonGeckoCom/NeonCore#egg=neon_core action/skill/
      - name: Test Skill Intents Padacioso
        if: ${{ inputs.test_padacioso }}
        run: |
          export INTENT_ENGINE="padacioso"
          export INTENT_TEST_FILE="action/skill/${{inputs.intent_file}}"
          pytest action/github/test/test_skill_intents.py
      - name: Test Skill Intents Padatious
        if: ${{ inputs.test_padatious }}
        run: |
          export INTENT_ENGINE="padatious"
          export INTENT_TEST_FILE="action/skill/${{inputs.intent_file}}"
          pytest action/github/test/test_skill_intents.py