name: Skill Unit Tests
on:
  workflow_call:
    inputs:
      skill_module:
        type: string
        required: true
      skill_class:
        type: string
        required: true
jobs:
  test_intents_ovos:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: action/skill/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v2
        with:
          repository: NeonGeckoCom/.github
          path: action/github/
          ref: FEAT_SharedSkillTests
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt install -y gcc libfann-dev swig libssl-dev portaudio19-dev git libpulse-dev
          pip install --upgrade pip
          pip install pytest mock ovos-core[skills] action/skill/
      - name: Test Skill Intents
        run: |
          export INTENT_TEST_FILE="action/skill/test/test_intents.yaml"
          pytest action/github/test/test_skill_intents.py
  test_intents_neon:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: [ 3.7, '3.10' ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: action/skill/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v2
        with:
          repository: NeonGeckoCom/.github
          path: action/github/
          ref: FEAT_SharedSkillTests
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt install -y gcc libfann-dev swig libssl-dev portaudio19-dev git libpulse-dev
          pip install --upgrade pip
          pip install pytest mock git+https://github.com/NeonGeckoCom/NeonCore#egg=neon_core action/skill/
      - name: Test Skill Intents
        run: |
          export INTENT_TEST_FILE="action/skill/test/test_intents.yaml"
          pytest action/github/test/test_skill_intents.py