name: Skill Unit Tests
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"
jobs:
  neon_core:
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, '3.10' ]
    runs-on: ${{inputs.runner}}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc libfann-dev swig libssl-dev portaudio19-dev git libpulse-dev
          pip install --upgrade pip
          pip install wheel "cython<3.0.0"  # TODO: cython patching https://github.com/yaml/pyyaml/issues/724
          pip install --no-build-isolation pyyaml~=5.4  # TODO: patching https://github.com/yaml/pyyaml/issues/724
          pip install pytest mock git+https://github.com/NeonGeckoCom/NeonCore#egg=neon_core
          pip install .
      - name: Test Skill
        run: |
          pytest test/test_skill.py
  ovos-core:
    strategy:
      matrix:
        python-version: [ 3.8 ]
    runs-on: ${{inputs.runner}}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc libfann-dev swig libssl-dev portaudio19-dev git libpulse-dev
          pip install --upgrade pip
          pip install wheel "cython<3.0.0"  # TODO: cython patching https://github.com/yaml/pyyaml/issues/724
          pip install --no-build-isolation pyyaml~=5.4  # TODO: patching https://github.com/yaml/pyyaml/issues/724
          pip install ovos-core[skills] pytest mock
          pip install .
      - name: Test Skill
        run: |
          pytest test/test_skill.py