name: Skill Unit Tests
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"
      intent_file:
        type: string
        default: test/test_intents.yaml
      timeout:
        type: number
        default: 15
      test_padatious:
        type: boolean
        default: False
      test_padacioso:
        type: boolean
        default: True
      neon_versions:
        type: string
        default: "[ 3.7, 3.8, 3.9, '3.10' ]"
      ovos_versions:
        type: string
        default: "[ 3.8, '3.10' ]"
jobs:
  test_intents_ovos:
    if: "${{ inputs.ovos_versions != '' }}"
    runs-on: ${{inputs.runner}}
    timeout-minutes: ${{inputs.timeout}}
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.ovos_versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: action/skill/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: NeonGeckoCom/.github
          path: action/github/
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc libfann-dev swig libssl-dev portaudio19-dev git libpulse-dev
          pip install --upgrade pip
          pip install wheel "cython<3.0.0"  # TODO: cython patching https://github.com/yaml/pyyaml/issues/724
          pip install --no-build-isolation pyyaml~=5.4  # TODO: patching https://github.com/yaml/pyyaml/issues/724
          pip install pytest mock ovos-core[skills,skills_lgpl]>=0.0.7 action/skill/
      - name: Test Skill Intents Padacioso
        if: ${{ inputs.test_padacioso }}
        run: |
          export INTENT_ENGINE="padacioso"
          export INTENT_TEST_FILE="action/skill/${{inputs.intent_file}}"
          pytest action/github/test/test_skill_intents.py
      - name: Test Skill Intents Padatious
        if: ${{ inputs.test_padatious }}
        run: |
          export INTENT_ENGINE="padatious"
          export INTENT_TEST_FILE="action/skill/${{inputs.intent_file}}"
          pytest action/github/test/test_skill_intents.py
  test_intents_neon:
    if: "${{ inputs.neon_versions != '' }}"
    runs-on: ${{inputs.runner}}
    timeout-minutes: ${{inputs.timeout}}
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.neon_versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: action/skill/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: NeonGeckoCom/.github
          path: action/github/
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc libfann-dev swig libssl-dev portaudio19-dev git libpulse-dev
          pip install --upgrade pip
          pip install pytest mock git+https://github.com/NeonGeckoCom/NeonCore@master#egg=neon_core action/skill/
      - name: Test Skill Intents Padacioso
        if: ${{ inputs.test_padacioso }}
        run: |
          export INTENT_ENGINE="padacioso"
          export INTENT_TEST_FILE="action/skill/${{inputs.intent_file}}"
          pytest action/github/test/test_skill_intents.py
      - name: Test Skill Intents Padatious
        if: ${{ inputs.test_padatious }}
        run: |
          export INTENT_ENGINE="padatious"
          export INTENT_TEST_FILE="action/skill/${{inputs.intent_file}}"
          pytest action/github/test/test_skill_intents.py