name: Skill Unit Tests
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"
      neon_versions:
        type: string
        default: "[ 3.8, 3.9, '3.10', '3.11' ]"
      ovos_versions:
        type: string
        default: "[ 3.8, '3.10' ]"
jobs:
  neon_core:
    if: "${{ inputs.neon_versions != '' }}"
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.neon_versions) }}
    runs-on: ${{inputs.runner}}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc libfann-dev swig libssl-dev portaudio19-dev git libpulse-dev
          pip install --upgrade pip
          pip install wheel "cython<3.0.0"  # TODO: cython patching https://github.com/yaml/pyyaml/issues/724
          pip install --no-build-isolation pyyaml~=5.4  # TODO: patching https://github.com/yaml/pyyaml/issues/724
          pip install pytest mock git+https://github.com/NeonGeckoCom/NeonCore#egg=neon_core .[test]
          # TODO: `mock` left for backwards-compat. skills should specify their own test deps
      - name: Test Skill
        run: |
          pytest test/test_skill.py
  ovos-core:
    if: "${{ inputs.ovos_versions != '' }}"
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.ovos_versions) }}
    runs-on: ${{inputs.runner}}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc libfann-dev swig libssl-dev portaudio19-dev git libpulse-dev
          pip install --upgrade pip
          pip install wheel "cython<3.0.0"  # TODO: cython patching https://github.com/yaml/pyyaml/issues/724
          pip install --no-build-isolation pyyaml~=5.4  # TODO: patching https://github.com/yaml/pyyaml/issues/724
          pip install ovos-core[skills]>=0.0.7 pytest mock .[test]
          # TODO: `mock` left for backwards-compat. skills should specify their own test deps
      - name: Test Skill
        run: |
          pytest test/test_skill.py
