name: Update skill.json
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"

jobs:
  update_skill_json:
    runs-on: ${{inputs.runner}}
    timeout-minutes: 15
    steps:
      - name: Checkout Skill Repository
        uses: actions/checkout@v4
        with:
          path: action/skill/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          path: action/github/
          repository: NeonGeckoCom/.github
          ref: FEAT_UpdateSkillMetaParsing
          # TODO: Remove ref before merge
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc git libpulse-dev
          pip install --upgrade pip
          pip install wheel numpy  # numpy patching https://github.com/benfred/parsesetup/issues/3
          pip install -r action/github/scripts/requirements.txt
      - name: Get Updated skill.json
        run: |
          python3 action/github/scripts/update_skill_json.py action/skill
      - name: Push skill.json Change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update skill.json
          repository: action/skill/
