name: Update skill.json
on:
  workflow_call:

jobs:
  update_skill_json:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: action/skill/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v2
        with:
          path: action/github/
          repository: NeonGeckoCom/.github
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc git libpulse-dev
          pip install --upgrade pip
          pip install -r action/github/scripts/requirements.txt
      - name: Get Updated skill.json
        run: |
          python action/github/scripts/update_skill_json.py action/skill
      - name: Push skill.json Change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update skill.json
          repository: action/skill/
